repositories {
    exclusiveContent {
        forRepository { mavenCentral() }
        filter {
            includeGroup 'org.scala-lang'
            includeGroup 'org.scala-lang.modules'
        }
    }
    maven {
        name 'GTNH Public'
        url 'https://nexus.gtnewhorizons.com/repository/public/'
    }
    maven { url 'https://jitpack.io' }
}
