// SPDX-License-Identifier: LGPL-3.0-only
// Minecraft 1.12 block states as written by 1.12.2 Litematica, by HackerRouter, 2026.
package com.github.lunatrius.schematica.world.schematic;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.minecraft.nbt.NBTTagCompound;

/**
 * Every Minecraft 1.12 block state with its numeric id/metadata and its flattened 1.13 state, from the table that
 * modern Litematica uses to convert .litematic files older than version 5 (assets/schematica/data, generated by
 * tools/generate_legacy_block_states.py). Vanilla 1.7.10 blocks keep their 1.12 names and metadata.
 */
public final class LegacyBlockStates {
    private static final String RESOURCE = "/assets/schematica/data/legacy_block_states.txt";

    /** A 1.12 state: its id << 4 | meta, block name and flattened 1.13 state. */
    public static final class Entry {
        public final int idMeta;
        public final String name, modern;

        Entry(int idMeta, String name, String modern) { this.idMeta = idMeta; this.name = name; this.modern = modern; }

        public int meta() { return idMeta & 15; }
    }

    private static Map<String, String> written;
    private static Map<String, Entry> states;

    private LegacyBlockStates() {}

    private static synchronized void load() {
        if (states != null) return;
        Map<String, String> byBlock = new HashMap<>();
        Map<String, Entry> byState = new HashMap<>();
        try (InputStream stream = LegacyBlockStates.class.getResourceAsStream(RESOURCE)) {
            if (stream == null) throw new IOException("Missing " + RESOURCE);
            BufferedReader reader = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') continue;
                String[] parts = line.split("\t");
                int idMeta = Integer.parseInt(parts[0]);
                String name = name(parts[2]);
                Entry entry = new Entry(idMeta, name, parts[1]);
                byBlock.putIfAbsent(name + '\0' + (idMeta & 15), parts[2]);
                for (int i = 2; i < parts.length; i++) byState.putIfAbsent(parts[i], entry);
            }
        } catch (IOException | RuntimeException e) {
            throw new IllegalStateException("Could not load the legacy block state table", e);
        }
        written = byBlock;
        states = byState;
    }

    static String name(String state) {
        int bracket = state.indexOf('[');
        return bracket < 0 ? state : state.substring(0, bracket);
    }

    /** The 1.12 state written for a block name and metadata, or null for blocks and values 1.12 does not have. */
    public static String state(String name, int meta) {
        load();
        return written.get(name + '\0' + meta);
    }

    /** The table entry of a 1.12 state string, or null when it is not a vanilla 1.12 state. */
    public static Entry entry(String state) {
        load();
        return states.get(state);
    }

    /** name[key=value,...] with sorted keys, the form used by the table. */
    public static String state(String name, Map<String, String> properties) {
        if (properties.isEmpty()) return name;
        List<String> keys = new ArrayList<>(properties.keySet());
        Collections.sort(keys);
        StringBuilder builder = new StringBuilder(name).append('[');
        for (int i = 0; i < keys.size(); i++) {
            if (i > 0) builder.append(',');
            builder.append(keys.get(i)).append('=').append(properties.get(keys.get(i)));
        }
        return builder.append(']').toString();
    }

    /** The state of a palette entry ({Name, Properties}). */
    public static String state(NBTTagCompound entry) {
        Map<String, String> properties = new HashMap<>();
        NBTTagCompound tag = entry.getCompoundTag("Properties");
        for (Object key : tag.func_150296_c()) properties.put((String) key, tag.getString((String) key));
        return state(entry.getString("Name"), properties);
    }

    /** A palette entry for a state string. */
    public static NBTTagCompound tag(String state) {
        NBTTagCompound tag = new NBTTagCompound();
        int bracket = state.indexOf('[');
        tag.setString("Name", bracket < 0 ? state : state.substring(0, bracket));
        if (bracket >= 0) {
            NBTTagCompound properties = new NBTTagCompound();
            for (String pair : state.substring(bracket + 1, state.length() - 1).split(",")) {
                int equals = pair.indexOf('=');
                properties.setString(pair.substring(0, equals), pair.substring(equals + 1));
            }
            tag.setTag("Properties", properties);
        }
        return tag;
    }
}
